version: '3.4'

services:
  gunicorn:
    image: tracker-app
    build:
      context: .
      target: tracker-gunicorn
  daphne:
    image: tracker-channels
    build:
      context: .
      target: tracker-daphne
  web:
    build:
      context: .
      target: web-nginx
    ports:
      - 8080:80
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    volumes:
      - tracker-db:/var/lib/postgresql/data
  redis:
    image: redis
volumes:
  tracker-db: